name: PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller click requests prettytable

      - name: Build executable
        run: |
          pyinstaller --onefile gladia_cli.py --hidden-import=click --hidden-import=requests --hidden-import=prettytable

      - name: Upload release
        uses: yakuhzi/action-release@v1
        with:
          file: ./dist/gladia_cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

